name: ReleaseWorkflow

on:
  push:
    branches:
      - master
      - staging

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm i @sentry/cli
      - run: export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
      - run: export SENTRY_ORG=bozdoz
      - run: export SENTRY_PROJECT=tws
      - run: export VERSION=$(node -e "console.log(require('./package.json').version)")
      - run: npx sentry-cli releases new -p $SENTRY_PROJECT $VERSION
      - run: npx sentry-cli releases set-commits --auto $VERSION
      - run: npx sentry-cli releases files $VERSION upload-sourcemaps dist/
      - run: npx sentry-cli releases finalize $VERSION